# Generated by Django 3.2 on 2021-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
