# Generated by Django 3.2 on 2021-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donationrequest_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')]),
        ),
    ]
