# Generated by Django 3.2 on 2021-08-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_alter_donationrequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='description',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
