# Generated by Django 3.2 on 2021-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_auto_20210830_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
