# Generated by Django 3.2 on 2021-08-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_alter_donationrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='searchSlug',
            field=models.SlugField(null=True),
        ),
    ]
