# Generated by Django 3.2 on 2021-08-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_donationrequest_searchslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequest',
            old_name='searchSlug',
            new_name='search_slug',
        ),
    ]
