# Generated by Django 3.2 on 2021-08-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_rename_searchslug_donationrequest_search_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
