# Generated by Django 3.2 on 2021-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_donationrequest_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='search_slug',
            field=models.SlugField(default=''),
        ),
    ]
