# Generated by Django 3.2 on 2021-09-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_auto_20210901_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
