# Generated by Django 3.2 on 2021-09-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0013_auto_20210908_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'),
                                   ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'Ab Positive'), ('AB-', 'Ab Negative')], max_length=3),
        ),
    ]
