# Generated by Django 3.2 on 2021-10-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0014_alter_donationrequest_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequest',
            old_name='time',
            new_name='date_required',
        ),
    ]
