# Generated by Django 3.2 on 2021-10-06 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0015_rename_time_donationrequest_date_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='date_required',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
