# Generated by Django 3.2 on 2021-07-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210729_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'Apositive'), ('A-', 'Anegative'), ('B+', 'Bpositive'), ('B-', 'Bnegative'), ('O+', 'Opositive'), ('O-', 'Onegative'), ('AB+', 'Abpositive'), ('AB-', 'Abnegative')], max_length=3, null=True),
        ),
    ]
