# Generated by Django 3.2 on 2021-08-16 07:37

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_alter_my_user_blood_group'),
    ]

    operations = [
        migrations.RenameModel('my_user', 'User'),
    ]
